# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  sync_stock_prices:
    class: SyncStockPricesJob
    schedule: every weekday at 14:30
  sync_stock_pers:
    class: SyncStockPersJob
    schedule: every weekday at 14:35
  poll_intraday_quotes:
    class: PollIntradayQuotesJob
    schedule: "*/3 9-13 * * 1-5"

development:
  sync_stock_prices:
    class: SyncStockPricesJob
    schedule: every weekday at 14:30
  sync_stock_pers:
    class: SyncStockPersJob
    schedule: every weekday at 14:35
  poll_intraday_quotes:
    class: PollIntradayQuotesJob
    schedule: "*/3 9-13 * * 1-5"
